AWSTemplateFormatVersion: '2010-09-09'
Parameters:
    SNSTestEmail:
        Type: String
        Default: Test@gmail.com
        Description: Enter email for SNS notification
Resources:
    AlertSNSTopic:
        Type: 'AWS::SNS::Topic'
        Properties:
            Subscription:
                - 
                    Endpoint:
                        Ref: SNSTestEmail
                    Protocol: email
    S3Bucket:
        Type: AWS::S3::Bucket
Outputs:
  BucketName:
    Value: !Ref 'S3Bucket'
    Description: Name of the sample Amazon S3 bucket.